# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'apham'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
  - name: Home
    link: /
  - name: People
    submenu:
      - name: faculty
        link: /members/faculty
      - name: Members
        link: /members/students
  - name: Publications
    link: /publications
  - name: Resources
    link: /resource
  - name: Events
    link: /events
  - name: Contact
    link: /contact

    
